sudo: required
services:
  - docker

before_install:
  - docker build -t raiyanrazi/docker-react -f Dockerfile.dev .

script:
  - docker run raiyanrazi/docker-react npm run coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-633516638445"
  bucket_path: "docker-react"
  on:
    branch: master
  local-dir: public